SELECT Avg(X.[2012]) OVER(ORDER BY [Miesiac] ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) "2012",
	Avg(X.[2013]) OVER(ORDER BY [Miesiac] ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) "2013"
FROM (
	SELECT DT.Rok [Rok], DT.Miesiac [Miesiac], FS.LineTotal [Kwota]
	FROM Pynka.FACT_SALES FS
	JOIN Pynka.DIM_TIME DT ON DT.PK_TIME=FS.OrderDate
	WHERE DT.Rok=2012 OR DT.Rok=2013) I
PIVOT(SUM([Kwota]) FOR I.[Rok] IN ([2012], [2013])) X;