CREATE TABLE Pynka.ENUM_MONTH (
	MONTH_ID INTEGER NOT NULL,
	MONTH_NAME VARCHAR(9) NOT NULL
);

INSERT INTO Pynka.ENUM_MONTH VALUES (1, 'January');
INSERT INTO Pynka.ENUM_MONTH VALUES (2, 'February');
INSERT INTO Pynka.ENUM_MONTH VALUES (3, 'March');
INSERT INTO Pynka.ENUM_MONTH VALUES (4, 'April');
INSERT INTO Pynka.ENUM_MONTH VALUES (5, 'May');
INSERT INTO Pynka.ENUM_MONTH VALUES (6, 'June');
INSERT INTO Pynka.ENUM_MONTH VALUES (7, 'July');
INSERT INTO Pynka.ENUM_MONTH VALUES (8, 'August');
INSERT INTO Pynka.ENUM_MONTH VALUES (9, 'September');
INSERT INTO Pynka.ENUM_MONTH VALUES (10, 'October');
INSERT INTO Pynka.ENUM_MONTH VALUES (11, 'November');
INSERT INTO Pynka.ENUM_MONTH VALUES (12, 'December');

CREATE TABLE Pynka.ENUM_WEEKDAY (
	WEEKDAY_ID INTEGER NOT NULL,
	WEEKDAY_NAME VARCHAR(9) NOT NULL
);

INSERT INTO Pynka.ENUM_WEEKDAY VALUES (1, 'Sunday');
INSERT INTO Pynka.ENUM_WEEKDAY VALUES (2, 'Monday');
INSERT INTO Pynka.ENUM_WEEKDAY VALUES (3, 'Tuesday');
INSERT INTO Pynka.ENUM_WEEKDAY VALUES (4, 'Wednesday');
INSERT INTO Pynka.ENUM_WEEKDAY VALUES (5, 'Thursday');
INSERT INTO Pynka.ENUM_WEEKDAY VALUES (6, 'Friday');
INSERT INTO Pynka.ENUM_WEEKDAY VALUES (7, 'Saturday');