SELECT CASE 
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=1 THEN 'Niedziela'
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=2 THEN 'Poniedzia³ek'
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=3 THEN 'Wtorek'
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=4 THEN 'Œroda'
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=5 THEN 'Czwartek'
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=6 THEN 'Pi¹tek'
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=7 THEN 'Sobota'
	END "Dzieñ tygodnia", SUM(SOH.SubTotal) "Suma", 
	COUNT(DISTINCT SOD.ProductID) "Liczba ró¿nych produktów"
	FROM Sales.SalesOrderHeader SOH
	JOIN Sales.SalesOrderDetail SOD ON SOH.SalesOrderID=SOD.SalesOrderID
	GROUP BY DATEPART(WEEKDAY, SOH.OrderDate) ORDER BY CASE
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=1 THEN 7
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=2 THEN 1
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=3 THEN 2
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=4 THEN 3
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=5 THEN 4
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=6 THEN 5
		WHEN DATEPART(WEEKDAY, SOH.OrderDate)=7 THEN 6
	END;